name: Issue Closed V2

on:
  issues:
    types: [closed]

jobs:
  update-airtable:
    runs-on: ubuntu-latest
    steps:
      - name: Check Repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with: 
          node-version: '16'

      - name: Install axios
        run: npm install axios
        
      - name: Execute Script
        uses: actions/github-script@v5
        env: 
          AIRTABLE_TOKEN: 'patM4RDthL4UGB7ah.3c7ad13af02bc9c5d838a6c7a19d3dadc43b52fe6d3ebed2935d5964e61bd089' #store into Airtable secret and change this to ${{ secrets.AIRTABLE_TOKEN}}
        with:
          script:  |
            const axios = require('axios');
            const regex = /Airtable ID:\n(.+)/g;
            const modifiedBody = (context.payload.issue.body.match(regex))[0].split('\n')[1];

            console.log('this is mod body' , modifiedBody);
            console.log('this is context payload', context.payload.issue.body);
            
            const body = {
              "records": [
                {
                  "id": modifiedBody,
                  "fields": {
                    "Status": "UAT"
                  }
                }
              ]
            }

            axios.patch(
              'https://api.airtable.com/v0/appO3Dnw1AxvkmGZx/Internal%20List',
              body,
              {
                headers:{
                'Authorization': `Bearer ${process.env.AIRTABLE_TOKEN}`,
                'Content-Type': 'application/json'
                }
              }
            ).catch(error => {
              console.error(`Error while updating with message: `, error.response.data);
              process.exit(1);
            });
